# Generated by Django 2.2.4 on 2022-03-11 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 13, 23, 10, 842303, tzinfo=utc)),
        ),
    ]
